#
#  █████████████████████████████████████████████
#  █─▄▄▄▄█─▄─▄─██▀▄─██▄─▄▄▀█─▄▄▄▄█─█─█▄─▄█▄─▄▄─█
#  █▄▄▄▄─███─████─▀─███─▄─▄█▄▄▄▄─█─▄─██─███─▄▄▄█
#  ▀▄▄▄▄▄▀▀▄▄▄▀▀▄▄▀▄▄▀▄▄▀▄▄▀▄▄▄▄▄▀▄▀▄▀▄▄▄▀▄▄▄▀▀▀
#
#  Starship Config
#  https://starship.rs
#

"$schema" = "https://starship.rs/config-schema.json"

format = """
[](fg:red bg:base)\
[](bg:peach fg:red)\
[](bg:yellow fg:peach)\
[](bg:green fg:yellow)\
[](bg:sapphire fg:green)\
[](bg:mauve fg:sapphire)\
[](bg:surface0 fg:mauve)\
$directory\
[](fg:surface0 bg:surface1)\
$git_branch\
[](fg:surface1 bg:surface2)\
$character\
[](fg:surface2) \
"""

add_newline = true
palette = "catppuccin_mocha"

[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "fg:text bg:surface0"
format = "[ $path ]($style)"

[git_branch]
symbol = "[](fg:subtext0 bg:surface1)"
style = "fg:text bg:surface1"
format = "[ $symbol $branch ]($style)"

[character]
success_symbol = "[✔](fg:green bg:surface2)"
error_symbol = "[✘](fg:red bg:surface2)"
format = "[ $symbol ](bg:surface2)"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
